language: clojure
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.m2
script:
  - lein test
  - lein test-cljs
after_success:
  - CLOVERAGE_VERSION=1.1.2 lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
